import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className="light">
      <body>
        <Providers>
          <Header />
          <main className="max-w-screen-lg mx-auto pt-20">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
